authy/urls.py
from django.urls import path
from authy.views import login_view, profile_view, workers_view, login_page
from django.contrib.auth import views as auth_views

urlpatterns = [
    
    path('', login_page, name='login'),
    path('login/', login_view, name='login_view'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<str:username>', profile_view, name='profile'),
    path('workers/', workers_view, name='workers'),
]

inmanage/urls.py
from django.contrib import admin
from django.urls import path, include
from inmanage.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('authy/', include('authy.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authy/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=150, blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True, null=True)
    adress = models.CharField(max_length=30, blank=True, null=True)
    city = models.CharField(max_length=30, blank=True, null=True)
    plz = models.CharField(max_length=30, blank=True, null=True)
    picture = models.ImageField(upload_to='profile_pics', blank=True, null=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

authy/forms.py
from django import forms
from authy.models import Profile
from django.contrib.auth.models import User, Group

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'bio', 'adress', 'city', 'plz', 'picture']

class StaffCreateForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    groups = forms.ModelMultipleChoiceField(
        queryset=Group.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = User
        fields = ("username", "email", "groups")

    def save(self, commit=True):
        user = super(StaffCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.set_unusable_password()
        if commit:
            user.save()
            user.groups.set(self.cleaned_data["groups"])
        return user

authy/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.urls import reverse
from authy.forms import ProfileForm, StaffCreateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.http import JsonResponse
import json 

def login_page(request):
    return render(request, 'authy/login.html')

def login_view(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        username = data.get('username')
        password = data.get('password')
        user = authenticate(request, username=username, password=password)

        if not user:
            return JsonResponse({'error': 'Invalid credentials'}, status=401)
        login(request, user)

        return JsonResponse({'redirectUrl': reverse('workers')})

@login_required
def profile_view(request, username):
    # the username is added in here just to make the url dynamic
    form = ProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)
    if request.method == 'POST':
        if form.is_valid():
            profile = form.save(commit=False)
            profile.save()
    return render(request, 'authy/profile.html', {'form': form})

@login_required
def workers_view(request):
    users = User.objects.exclude(id=request.user.id)
    search = request.GET.get('search')
    if search:
        users = users.filter(username__icontains=search)

    if request.method == 'POST':
        form = StaffCreateForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = StaffCreateForm()

    groups = Group.objects.all()

    context = {'users': users, 'form': form, 'groups': groups}
    
    return render(request, 'authy/workers.html', context)

inmanage/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    return render(request, 'home.html')

inmanage/templates/authy/login.html
{% load static %}

<!DOCTYPE html>
<html>

<head style="background-color: rgb(41, 30, 61) !important;">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Security-Policy" content="Content-Security-Policy: default-src 'self' *.googleapis.com">
    <title>Registrieren</title>
    <link rel="stylesheet" href="{% static 'css/loginStyles.css' %}">
</head>

<body>
    <div class="login-container">
        <div class="login-logo">
            <img src="{% static 'icons/inManage.png' %}" alt="InManage Logo">
        </div>
        <h2>Willkommen bei InManage</h2>

        <form id="loginForm" class="login" method="POST" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="form-group input-group">
                <label for="id_username">Benutzername</label>
                <input type="text" name="username" id="id_username" class="form-control"
                    placeholder="Geben Sie Ihren Benutzernamen" required>
            </div>
            <div class="form-group input-group">
                <label for="id_password">Passwort</label>
                <input type="password" name="password" id="id_password" class="form-control"
                    placeholder="Geben Sie Ihr Passwort" required>
            </div>
            <button class="login-button" type="submit">Anmeldung</button>
        </form>

    </div>
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        document.getElementById('loginForm').addEventListener('submit', function (event) {
            event.preventDefault();

            var username = document.getElementById('id_username').value;
            var password = document.getElementById('id_password').value;
            // AJAX request to the server
            fetch("{% url 'login_view' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    "X-CSRFToken": getCookie('csrftoken')
                },
                mode: "same-origin",
                body: JSON.stringify({ username: username, password: password })
            })
                .then(response => {
                    if (response.ok) {
                        return response.json();
                    } else {
                        throw new Error('Authentication failed');
                    }
                })
                .then(data => {
                    window.location.href = data.redirectUrl;
                })
                .catch(error => {
                    console.error('Error:', error);
                });
        });
    </script>
</body>

</html>

inmanage/templates/authy/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="profile-container">
    <div class="profile-header">
        <div class="avatar">
            {% if request.user.profile.picture %}
            <img class="avatar-img" style="width: 100px; height: 100px; border-radius: 25%;" src="{% if request.is_secure %}https{% else %}http{% endif %}://{{request.META.HTTP_HOST}}{{ request.user.profile.picture.url }}" alt="Profile Picture">
            {% endif %}
        </div>
        <div class="profile-info">
            {% if request.user.profile.first_name %}
            <h1>{{ request.user.profile.first_name }} {{ request.user.profile.last_name }}</h1>
            {% else %}
            <h1>{{ request.user.username }}</h1>
            {% endif %}
            <button id="editProfile" onclick="enableForm()">Edit</button>
        </div>
    </div>

    <form id="profileForm" class="profile-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <label for="id_picture">Picture</label>
            <input type="file" id="id_picture" name="picture" accept="image/*" disabled>
        </div>
        <div class="form-row">
            <label for="id_first_name">First Name</label>
            <input type="text" id="id_first_name" name="first_name" value="{{ form.first_name.value }}" disabled>
        </div>
        <div class="form-row">
            <label for="id_last_name">Last Name</label>
            <input type="text" id="id_last_name" name="last_name" value="{{ form.last_name.value }}" disabled>
        </div>
        <div class="form-row">
            <label for="id_city">City</label>
            <input type="text" id="id_city" name="city" value="{{ form.city.value }}" disabled>
        </div>
        <div class="form-row">
            <label for="id_plz">PLZ</label>
            <input type="text" id="id_plz" name="plz" value="{{ form.plz.value }}" disabled>
        </div>
        <div class="form-row">
            <label for="id_adress">Address</label>
            <input type="text" id="id_adress" name="adress" value="{{ form.adress.value }}" disabled>
        </div>
        <div class="form-row">
            <label for="id_bio">Bio</label>
            <textarea id="id_bio" name="bio" disabled>{{ form.bio.value }}</textarea>
        </div>
        <button type="submit" id="confirmEdit" style="display: none;">Confirm</button>
    </form>
</main>

<script>
    function enableForm() {
        document.querySelectorAll('#profileForm input').forEach(input => input.disabled = false);
        document.querySelectorAll('#profileForm textarea').forEach(input => input.disabled = false);

        document.getElementById('confirmEdit').style.display = 'block';
    }
</script>
{% endblock %}

inmanage/templates/authy/workers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main class="mitarbeiter-container">
    <h1>Arbeitskräfte</h1>

    <div class="search-container">
        <form method="GET">
            {% csrf_token %}
            <input type="text" name="search" value="{{ request.GET.search }}" placeholder="Search by Username">
        </form>
        <!-- <input type="text" placeholder=""> -->
        <button class="add-staff" id="addStaff">+ Add Staff Member</button>
    </div>

    <div class="staff-grid">
        {% for user in users %}
        <div class="staff-card">
            <div class="avatar">
                {% if user.profile.picture %}
                <img class="avatar-img" style="width: 100px; height: 100px; border-radius: 25%;"
                    src="{{ user.profile.picture.url }}" alt="Profile Picture">
                {% else %}
                <img class="avatar-img" style="width: 100px; height: 100px; border-radius: 25%;"
                    src="{% static 'icons/profile.png' %}" alt="Profile Picture">
                {% endif %}
            </div>
            <div class="staff-info">
                <h2>{{ user.username }}</h2>

                <p>User Groups</p>
                <div class="groups">
                    {% for group in user.groups.all %}
                    <span>{{group}}</span>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>

<div class="modal" id="addStaffModal">
    <div class="modal-content">
        <span class="close-button" id="closeModal">&times;</span>
        <h2>Add Staff Member</h2>
        <form id="userCreationForm" class="profile-form" method="post">
            {% csrf_token %}
            <div class="form-row">
                <label for="id_username">Username</label>
                <input type="text" id="id_username" name="username" required>
            </div>
            <div class="form-row">
                <label for="id_email">Email</label>
                <input type="email" id="id_email" name="email" required>
            </div>
            <div class="form-row">
                <label for="id_groups">Groups</label>
                <select id="id_groups" name="groups" multiple>
                    {% for group in groups %}
                    <option value="{{ group.id }}">{{ group.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-row">
            </div>
            <button type="submit" id="confirmEdit">Add member</button>
        </form>
    </div>
</div>

<script>
    document.querySelector('.add-staff').addEventListener('click', function () {
    });

    document.getElementById('addStaff').addEventListener('click', function () {
        document.getElementById('addStaffModal').style.display = 'block';
    });

    document.getElementById('closeModal').addEventListener('click', function () {
        document.getElementById('addStaffModal').style.display = 'none';
    });

    document.getElementById('addStaffForm').addEventListener('submit', function (event) {
        event.preventDefault();

        document.getElementById('addStaffModal').style.display = 'none';
    });

    window.onclick = function (event) {
        const modal = document.getElementById('addStaffModal');
        if (event.target == modal) {
            modal.style.display = 'none';
        }
    };
</script>
{% endblock %}

inmanage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head style="background-color: rgb(41, 30, 61) !important;">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Security-Policy" content="Content-Security-Policy: default-src 'self' *.googleapis.com">
    <title>Inmanage</title>
    <link rel="stylesheet" href="{% static 'css/profileStyles.css' %}">
    <link rel="stylesheet" href="{% static 'css/mitarbeiterStyles.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    {% include 'navbar.html' %}
    <main>
        {% block content%}
    </main>
    {% endblock %}
</body>

</html>

inmanage/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% endblock %}

inmanage/templates/navbar.html
{% load static %}
<header class="navbar">
  <div class="nav-left">
    <div class="logo">
      <img src="{% static 'icons/inManage.png' %}" alt="InManage Logo">
    </div>
    <nav class="nav-links">
      <a href="{% url 'workers' %}">Mitarbeiter Management</a>
      <a href="{% url 'profile' user.username %}">Profile</a>
    </nav>
  </div>
  <div class="navbar-section user-info">
    <span>Hello! {{ user.username }}</span>
    <a href="{% url 'logout' %}"><button id="logoutButton">Log out</button></a>
  </div>
</header>